// File: kamus-data.js
// Berisi daftar kosakata Indonesia - Wolio beserta pelafalan dan tipe katanya.
// Data sudah diurutkan berdasarkan 'indonesia' untuk Binary Search.
// PERHATIAN: Data Wolio di bawah ini hanya contoh ilustratif. Ganti dengan data yang akurat.

let dataKamus = [
    { indonesia: 'air', wolio: 'ae', pelafalan: 'a-e', tipe: 'kata benda' },
    { indonesia: 'aku', wolio: 'iaku', pelafalan: 'i-a-ku', tipe: 'pronomina' },
    { indonesia: 'anda', wolio: 'ingko', pelafalan: 'ing-ko', tipe: 'pronomina' },
    { indonesia: 'anjing', wolio: 'kapili', pelafalan: 'ka-pi-li', tipe: 'kata benda' },
    { indonesia: 'api', wolio: 'afu', pelafalan: 'a-fu', tipe: 'kata benda' },
    { indonesia: 'ayam', wolio: 'manukolo', pelafalan: 'ma-nu-ko-lo', tipe: 'kata benda' },
    { indonesia: 'baca', wolio: 'basa', pelafalan: 'ba-sa', tipe: 'kata kerja' },
    { indonesia: 'baju', wolio: 'badhu', pelafalan: 'ba-dhu', tipe: 'kata benda' },
    { indonesia: 'banyak', wolio: 'daoa', pelafalan: 'da-o-a', tipe: 'kata sifat' },
    { indonesia: 'baru', wolio: 'baru', pelafalan: 'ba-ru', tipe: 'kata sifat' },
    { indonesia: 'batu', wolio: 'watu', pelafalan: 'wa-tu', tipe: 'kata benda' },
    { indonesia: 'bekerja', wolio: 'bubu', pelafalan: 'bu-bu', tipe: 'kata kerja' },
    { indonesia: 'belajar', wolio: 'mompelajari', pelafalan: 'mom-pe-la-ja-ri', tipe: 'kata kerja' },
    { indonesia: 'beli', wolio: 'boli', pelafalan: 'bo-li', tipe: 'kata kerja' },
    { indonesia: 'benar', wolio: 'tunu', pelafalan: 'tu-nu', tipe: 'kata sifat' },
    { indonesia: 'berbicara', wolio: 'bibici', pelafalan: 'bi-bi-ci', tipe: 'kata kerja' },
    { indonesia: 'besar', wolio: 'oge', pelafalan: 'o-ge', tipe: 'kata sifat' },
    { indonesia: 'datang', wolio: 'amai', pelafalan: 'a-mai', tipe: 'kata kerja' },
    { indonesia: 'dia', wolio: 'incia', pelafalan: 'in-ci-a', tipe: 'pronomina' },
    { indonesia: 'duduk', wolio: 'meende', pelafalan: 'me-en-de', tipe: 'kata kerja' },
    { indonesia: 'ikan', wolio: 'bau', pelafalan: 'ba-u', tipe: 'kata benda' },
    { indonesia: 'ini', wolio: 'a\'i', pelafalan: 'a-i', tipe: 'penentu' },
    { indonesia: 'itu', wolio: 'a\'o', pelafalan: 'a-o', tipe: 'penentu' },
    { indonesia: 'jangan', wolio: 'ne\'e', pelafalan: 'ne-e', tipe: 'kata keterangan' },
    { indonesia: 'jual', wolio: 'popasa', pelafalan: 'po-pa-sa', tipe: 'kata kerja' },
    { indonesia: 'kaki', wolio: 'kadondo', pelafalan: 'ka-don-do', tipe: 'kata benda' },
    { indonesia: 'kamu', wolio: 'ingko', pelafalan: 'ing-ko', tipe: 'pronomina' },
    { indonesia: 'karena', wolio: 'sababu', pelafalan: 'sa-ba-bu', tipe: 'konjungsi' },
    { indonesia: 'kecil', wolio: 'kido', pelafalan: 'ki-do', tipe: 'kata sifat' },
    { indonesia: 'kepala', wolio: 'ubuna', pelafalan: 'u-bu-na', tipe: 'kata benda' },
    { indonesia: 'kucing', wolio: 'puti', pelafalan: 'pu-ti', tipe: 'kata benda' },
    { indonesia: 'laki-laki', wolio: 'rumaane', pelafalan: 'ru-maa-ne', tipe: 'kata benda' },
    { indonesia: 'lihat', wolio: 'bhone', pelafalan: 'bho-ne', tipe: 'kata kerja' },
    { indonesia: 'makan', wolio: 'komia', pelafalan: 'ko-mi-a', tipe: 'kata kerja' },
    { indonesia: 'malam', wolio: 'malona', pelafalan: 'ma-lo-na', tipe: 'kata benda' },
    { indonesia: 'mata', wolio: 'mata', pelafalan: 'ma-ta', tipe: 'kata benda' },
    { indonesia: 'minum', wolio: 'anginu', pelafalan: 'a-ngi-nu', tipe: 'kata kerja' },
    { indonesia: 'nama', wolio: 'ara', pelafalan: 'a-ra', tipe: 'kata benda' },
    { indonesia: 'orang', wolio: 'mia', pelafalan: 'mi-a', tipe: 'kata benda' },
    { indonesia: 'panas', wolio: 'mapaasu', pelafalan: 'ma-paa-su', tipe: 'kata sifat' },
    { indonesia: 'pasar', wolio: 'pasara', pelafalan: 'pa-sa-ra', tipe: 'kata benda' },
    { indonesia: 'perempuan', wolio: 'mawawine', pelafalan: 'ma-wa-wi-ne', tipe: 'kata benda' },
    { indonesia: 'pergi', wolio: 'lao', pelafalan: 'la-o', tipe: 'kata kerja' },
    { indonesia: 'rumah', wolio: 'banua', pelafalan: 'ba-nu-a', tipe: 'kata benda' },
    { indonesia: 'sakit', wolio: 'moisa', pelafalan: 'mo-i-sa', tipe: 'kata sifat' },
    { indonesia: 'satu', wolio: 'dise', pelafalan: 'di-se', tipe: 'numeralia' },
    { indonesia: 'saya', wolio: 'iaku', pelafalan: 'i-a-ku', tipe: 'pronomina' },
    { indonesia: 'siapa', wolio: 'isema', pelafalan: 'i-se-ma', tipe: 'kata tanya' },
    { indonesia: 'tidur', wolio: 'metinda', pelafalan: 'me-tin-da', tipe: 'kata kerja' },
    { indonesia: 'tangan', wolio: 'lima', pelafalan: 'li-ma', tipe: 'kata benda' }
];